"""ADD novas ligações

Revision ID: 3acf837617c7
Revises: 15c8353b7f1b
Create Date: 2022-07-01 03:54:18.645592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3acf837617c7'
down_revision = '15c8353b7f1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('produto_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pedido_usuario', 'usuario', ['usuario_id'], ['id'])
        batch_op.create_foreign_key('fk_pedido_produto', 'produto', ['produto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pedido_produto', type_='foreignkey')
        batch_op.drop_constraint('fk_pedido_usuario', type_='foreignkey')
        batch_op.drop_column('produto_id')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
