"""Correções

Revision ID: 5016fbe519f7
Revises: c9b515911af9
Create Date: 2022-07-01 04:09:07.348435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5016fbe519f7'
down_revision = 'c9b515911af9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
