"""Correção no banco

Revision ID: 8061aff09cb0
Revises: 5016fbe519f7
Create Date: 2022-07-04 05:03:33.602875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8061aff09cb0'
down_revision = '5016fbe519f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_index('ix_pedido_id')
        batch_op.create_index(batch_op.f('ix_pedido_id'), ['id'], unique=True)

    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_index('ix_produto_id')
        batch_op.create_index(batch_op.f('ix_produto_id'), ['id'], unique=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index('ix_usuario_id')
        batch_op.create_index(batch_op.f('ix_usuario_id'), ['id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_id'))
        batch_op.create_index('ix_usuario_id', ['id'], unique=False)

    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produto_id'))
        batch_op.create_index('ix_produto_id', ['id'], unique=False)

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_id'))
        batch_op.create_index('ix_pedido_id', ['id'], unique=False)

    # ### end Alembic commands ###
