"""ADD novas ligações correta

Revision ID: c9b515911af9
Revises: 3acf837617c7
Create Date: 2022-07-01 03:55:56.402803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b515911af9'
down_revision = '3acf837617c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
